### ISSUE TITLE
hbldr don´t open mednafen

### ISSUE THREAD

**Issue by gen04177** [ps5-payload-dev/shsrv#2] opened 2024-06-24 16:12 UTC
Escape character is '^]'.

**Welcome to shsrv.elf running on pid 77, compiled Jun 24 2024 at 13:16:14**

Model:          xxxxxxxxxxxx
S/N:               xxxxxxxxxxxx
S/W:                4.500.005
SoC temp:               44 °C
CPU temp:               46 °C
CPU freq:             800 MHz

Type 'help' for a list of commands

/$ cd data      
/data$ cd homebrew
/data/homebrew$ cd Mednafen
/data/homebrew/Mednafen$ hbldr mednafen.elf /data/homebrew/Mednafen/roms/Finally.wsc
[] W:\Build\J01795075\vsh\common_lib\lnc_util\src\lnc_util_ipc_client.cpp(382) getAppStatus: LNC_ISOK::0x80940004
pt_attach: File exists

**Comment by john-tornblom** [comment] 2024-06-24 16:18
It does load it, you need to export the env var
MEDNAFEN_HOME so the emulator knows where to find it’s config file.

 See:
https://mednafen.github.io/documentation/#Section_environment_variables




mån 24 juni 2024 kl. 18:13 skrev gen04177 ***@***.***>:

**Comment by gen04177** [comment] 2024-06-24 16:35
I updated the version of shsrv, please see the message above... in the previous version of shsrv I had already defined the variable: 

/data/homebrew/Mednafen$ env
MEDNAFEN_HOME=/data/homebrew/Mednafen
OLDPWD=/data/homebrew
PWD=/data/homebrew/Mednafen
PATH=/mnt/usb0/hbroot/bin:/data/hbroot/bin
HOME=/

**Comment by john-tornblom** [comment] 2024-06-24 16:54
Duplicate of #3

**Closed as completed by john-tornblom** 2024-06-24 16:54 UTC
